"""Stock-buying indicator reference.

Each indicator has:
  name, category, styles, summary, read (how to read it), source, tip,
  optional: link (where to view it live), fred_id (for macro indicators)

Categories: macro, valuation, quality, growth, technical, sentiment, alt, tool, framework
Styles: value, growth, momentum, macro, quality
"""
from __future__ import annotations

REGIME_TILES = [
    # Filled in dynamically by data.get_fred_series. Order matters.
    {"label": "Credit (HY OAS)", "fred_id": "BAMLH0A0HYM2",
     "thresholds": {"green": (None, 400), "amber": (400, 800), "red": (800, None)},
     "good": "low",
     "explain": "HY spread <400 = risk-on, 400-800 normal, >800 stress, >1000 crisis (historical buy zone)."},
    {"label": "Growth (ISM Mfg)", "fred_id": "NAPM",
     "thresholds": {"green": (50, None), "amber": (45, 50), "red": (None, 45)},
     "good": "high",
     "explain": ">50 = expansion, 45-50 contraction, <45 recession."},
    {"label": "Volatility (VIX)", "fred_id": "VIXCLS",
     "thresholds": {"green": (None, 20), "amber": (20, 30), "red": (30, None)},
     "good": "low",
     "explain": "<15 complacency, 15-25 normal, >30 fear, >40 panic / historical buy."},
    {"label": "Yield curve (2s10s)", "fred_id": "T10Y2Y",
     "thresholds": {"green": (0.5, None), "amber": (0, 0.5), "red": (None, 0)},
     "good": "high",
     "explain": "Inverted = recession signal. Steepening from inversion = late-cycle warning."},
    {"label": "CPI YoY", "fred_id": "CPIAUCSL",
     "thresholds": {"green": (None, 3), "amber": (3, 4), "red": (4, None)},
     "good": "low",
     "explain": "Fed target ~2%. Above 3% = sticky inflation, limits Fed easing room.",
     "yoy": True},
    {"label": "Unemployment", "fred_id": "UNRATE",
     "thresholds": {"green": (None, 4.5), "amber": (4.5, 5.5), "red": (5.5, None)},
     "good": "low",
     "explain": "Full employment ~4%. Sahm Rule triggers recession signal when 3mo avg rises 0.5pp above 12mo low."},
    {"label": "Dollar (DXY)", "fred_id": "DTWEXBGS",
     "thresholds": {"green": (None, 105), "amber": (105, 115), "red": (115, None)},
     "good": "low",
     "explain": "Strong dollar = headwind for multinationals, EM, commodities."},
]


# ---------------------------------------------------------------------------
# Full indicator definitions
# ---------------------------------------------------------------------------

INDICATORS = [
    # ============== MACRO ==============
    {"n": "Fed Funds Rate", "c": "macro", "s": ["macro"], "fred_id": "DFEDTARU",
     "m": "The Fed's overnight policy rate. Drives the rates complex and discount rate.",
     "r": "Cuts typically bullish for stocks. Hikes compress multiples. Watch the expected path via FF futures.",
     "src": "FRED (DFEDTARU), CME FedWatch",
     "tip": "Don't fight the Fed, but first cuts often arrive because economy is breaking.",
     "link": "https://fred.stlouisfed.org/series/DFEDTARU",
     "tgt": "Neutral rate ~2.5-3%. Above = restrictive. Below = accommodative.",
     "thresholds": {"green": (None, 3.5), "amber": (3.5, 5), "red": (5, None)}, "good": "low"},
    {"n": "10Y Treasury Yield", "c": "macro", "s": ["macro"], "fred_id": "DGS10",
     "m": "Benchmark long-rate. Drives equity multiples and mortgage rates.",
     "r": "Rising yields compress duration assets (tech, growth, gold). Falling = tailwind.",
     "src": "FRED (DGS10), Treasury.gov",
     "tip": "10Y > 5% has historically been multiple-killer territory.",
     "link": "https://fred.stlouisfed.org/series/DGS10",
     "tgt": "3-4% normal. >5% = restrictive.",
     "thresholds": {"green": (None, 4), "amber": (4, 5), "red": (5, None)}, "good": "low"},
    {"n": "Yield Curve - 2s10s", "c": "macro", "s": ["macro"], "fred_id": "T10Y2Y",
     "m": "10Y minus 2Y. Classic recession bellwether.",
     "r": "Inverted (negative) precedes recession 6-24mo. Steepening from inversion = actual trigger.",
     "src": "FRED (T10Y2Y)",
     "tip": "Un-inversion matters more than inversion itself.",
     "link": "https://fred.stlouisfed.org/series/T10Y2Y",
     "tgt": "Normal: +50 to +200 bps. Inverted = recession warning.",
     "thresholds": {"green": (0.5, None), "amber": (0, 0.5), "red": (None, 0)}, "good": "high"},
    {"n": "Yield Curve - 3m10y", "c": "macro", "s": ["macro"], "fred_id": "T10Y3M",
     "m": "10Y minus 3-month T-bill. NY Fed's preferred recession model.",
     "r": "Inversion has preceded every US recession since 1960 with few false positives.",
     "src": "FRED (T10Y3M)", "tip": "Less noisy than 2s10s.",
     "link": "https://fred.stlouisfed.org/series/T10Y3M",
     "tgt": "Healthy: >+100 bps. Inverted = recession risk rising.",
     "thresholds": {"green": (1.0, None), "amber": (0, 1.0), "red": (None, 0)}, "good": "high"},
    {"n": "Real Yields (10Y TIPS)", "c": "macro", "s": ["macro", "growth"], "fred_id": "DFII10",
     "m": "Inflation-adjusted 10Y yield. True cost of capital.",
     "r": "Rising real yields = kryptonite for long-duration assets (tech, growth, gold).",
     "src": "FRED (DFII10)", "tip": "Watch this more than nominal yields for growth-stock direction.",
     "link": "https://fred.stlouisfed.org/series/DFII10",
     "tgt": "Above 2% = restrictive. Below 0% = ultra-easy.",
     "thresholds": {"green": (None, 1.5), "amber": (1.5, 2.5), "red": (2.5, None)}, "good": "low"},
    {"n": "HY Credit Spread (OAS)", "c": "macro", "s": ["macro"], "fred_id": "BAMLH0A0HYM2",
     "m": "High-yield bond spread over Treasuries. The risk-appetite gauge.",
     "r": "<400 bps = euphoric. 500-700 = normal. >800 = stress. >1000 = crisis (often equity buy zone).",
     "src": "FRED (BAMLH0A0HYM2)",
     "tip": "Best forward-looking equity signal that isn't equity.",
     "link": "https://fred.stlouisfed.org/series/BAMLH0A0HYM2",
     "tgt": "Tight: <400. Normal: 500-700. Stress: >800. Crisis: >1000.",
     "thresholds": {"green": (None, 4), "amber": (4, 8), "red": (8, None)}, "good": "low"},
    {"n": "IG Credit Spread (OAS)", "c": "macro", "s": ["macro"], "fred_id": "BAMLC0A0CM",
     "m": "Investment-grade corporate spread over Treasuries.",
     "r": "<120 bps = risk-on. >200 bps = stress. Stocks usually follow credit.",
     "src": "FRED (BAMLC0A0CM)", "tip": "Credit leads equity.",
     "link": "https://fred.stlouisfed.org/series/BAMLC0A0CM",
     "tgt": "<100 = tight. 100-150 = normal. >200 = stressed.",
     "thresholds": {"green": (None, 1.5), "amber": (1.5, 2.5), "red": (2.5, None)}, "good": "low"},
    {"n": "ISM Manufacturing PMI", "c": "macro", "s": ["macro", "value"], "fred_id": "NAPM",
     "m": "Survey of US mfg purchasing managers. Diffusion index.",
     "r": ">50 = expansion. <50 = contraction. Trough <45 + rising = early-cycle buy.",
     "src": "ISM.org, FRED (NAPM)",
     "tip": "Cyclicals (industrials, materials, semis) rip when PMI bottoms and turns.",
     "link": "https://fred.stlouisfed.org/series/NAPM",
     "tgt": ">55 = strong. 50-55 = healthy. <45 = recession territory.",
     "thresholds": {"green": (50, None), "amber": (45, 50), "red": (None, 45)}, "good": "high"},
    {"n": "CPI YoY", "c": "macro", "s": ["macro"], "fred_id": "CPIAUCSL",
     "m": "Consumer Price Index year-over-year.",
     "r": "Higher than expected = hawkish Fed = multiples compress.",
     "src": "BLS, FRED (CPIAUCSL)",
     "tip": "Markets care about the surprise vs consensus, not absolute level.",
     "link": "https://fred.stlouisfed.org/series/CPIAUCSL",
     "tgt": "Fed target ~2%. Above 3% = sticky.",
     "thresholds": {"green": (None, 2.5), "amber": (2.5, 4), "red": (4, None)}, "good": "low", "yoy": True},
    {"n": "Core PCE YoY", "c": "macro", "s": ["macro"], "fred_id": "PCEPILFE",
     "m": "Personal Consumption Expenditures core. Fed's preferred inflation measure.",
     "r": "Fed target is 2% core PCE YoY. 3mo/6mo annualized rates are tighter signals.",
     "src": "BEA, FRED (PCEPILFE)",
     "tip": "When Powell quotes inflation, it's almost always core PCE.",
     "link": "https://fred.stlouisfed.org/series/PCEPILFE",
     "tgt": "Fed target 2%. Comfort zone 2-2.5%.",
     "thresholds": {"green": (None, 2.5), "amber": (2.5, 3.5), "red": (3.5, None)}, "good": "low", "yoy": True},
    {"n": "Unemployment Rate", "c": "macro", "s": ["macro"], "fred_id": "UNRATE",
     "m": "% of labor force unemployed. Sahm Rule triggers on 3mo avg rising 0.5pp above 12mo low.",
     "r": "Sahm Rule has called every US recession since 1970.",
     "src": "BLS, FRED (UNRATE)",
     "tip": "When unemployment turns, it turns hard.",
     "link": "https://fred.stlouisfed.org/series/UNRATE",
     "tgt": "Full employment 3.5-4%. Above 4.5% = warning zone.",
     "thresholds": {"green": (None, 4.5), "amber": (4.5, 5.5), "red": (5.5, None)}, "good": "low"},
    {"n": "Initial Jobless Claims", "c": "macro", "s": ["macro"], "fred_id": "ICSA",
     "m": "Weekly first-time unemployment filings.",
     "r": "<250k = strong labor. >350k = weakness. >400k sustained = recession.",
     "src": "DOL, FRED (ICSA)",
     "tip": "Highest-frequency hard data on the economy. Thursdays 8:30am ET.",
     "link": "https://fred.stlouisfed.org/series/ICSA",
     "tgt": "<250k = strong. >350k = weak.",
     "thresholds": {"green": (None, 250000), "amber": (250000, 350000), "red": (350000, None)}, "good": "low"},
    {"n": "Industrial Production", "c": "macro", "s": ["macro"], "fred_id": "INDPRO",
     "m": "Output of manufacturing, mining, utilities.",
     "r": "Falling IP = recession/slowdown. IP rolling over is a clean recession signal.",
     "src": "Federal Reserve, FRED (INDPRO)",
     "tip": "Pair with yield curve inversion for high-confidence recession signal.",
     "link": "https://fred.stlouisfed.org/series/INDPRO",
     "tgt": "Watch direction. YoY > 0 = expansion. Negative YoY persistent = recession.",
     "thresholds": {"green": (1, None), "amber": (-1, 1), "red": (None, -1)}, "good": "high", "yoy": True},
    {"n": "Housing Starts", "c": "macro", "s": ["macro"], "fred_id": "HOUST",
     "m": "New residential construction (permits lead starts).",
     "r": "Most rate-sensitive sector. Permits turning up after drawdown = early-cycle signal.",
     "src": "Census Bureau, FRED (HOUST)",
     "tip": "When permits troughed, homebuilders (XHB, ITB) ripped 50-100% in 12mo historically.",
     "link": "https://fred.stlouisfed.org/series/HOUST",
     "tgt": ">1500k = strong. 1200-1500k = normal. <1000k = weak.",
     "thresholds": {"green": (1300, None), "amber": (1100, 1300), "red": (None, 1100)}, "good": "high"},
    {"n": "Conference Board LEI", "c": "macro", "s": ["macro"], "fred_id": "USSLIND",
     "m": "Leading Economic Index - 10-component composite.",
     "r": "6mo annualized <-4% has called every recession since 1960.",
     "src": "Conference Board",
     "tip": "Slow but reliable. Turning positive after contraction = lean cyclical.",
     "link": "https://fred.stlouisfed.org/series/USSLIND",
     "tgt": "Positive = expansion. Negative + falling = recession risk.",
     "thresholds": {"green": (0.5, None), "amber": (-0.5, 0.5), "red": (None, -0.5)}, "good": "high"},
    {"n": "M2 Money Supply", "c": "macro", "s": ["macro"], "fred_id": "M2SL",
     "m": "Broad money - currency + checking + savings + small CDs.",
     "r": "Rapid growth (>10% YoY) historically inflationary 12-18mo later. Negative YoY = deflationary.",
     "src": "FRED (M2SL)",
     "tip": "M2 going negative in 2022-23 was an underrated signal.",
     "link": "https://fred.stlouisfed.org/series/M2SL",
     "tgt": "Healthy YoY: 4-8%. Excess: >10% (inflationary). Negative: deflationary.",
     "thresholds": {"green": (3, 8), "amber": (8, 12), "red": (12, None)}, "good": "low", "yoy": True},
    {"n": "DXY (Dollar Index)", "c": "macro", "s": ["macro"], "fred_id": "DTWEXBGS",
     "m": "USD vs basket of major currencies (broad, trade-weighted).",
     "r": "Strong dollar = headwind for US multinationals, EM, commodities.",
     "src": "FRED (DTWEXBGS)",
     "tip": "S&P EPS has ~10% inverse correlation to DXY for multinationals.",
     "link": "https://fred.stlouisfed.org/series/DTWEXBGS",
     "tgt": "Strong dollar (>120) = headwind for risk. Weak (<110) = tailwind.",
     "thresholds": {"green": (None, 115), "amber": (115, 125), "red": (125, None)}, "good": "low"},
    {"n": "WTI Crude Oil", "c": "macro", "s": ["macro"], "fred_id": "DCOILWTICO",
     "m": "WTI crude benchmark price.",
     "r": "Rising oil = inflation, hits consumer discretionary. Falling = disinflation tailwind.",
     "src": "EIA, FRED (DCOILWTICO)",
     "tip": "Oil shocks >40% in 6mo have preceded most US recessions.",
     "link": "https://fred.stlouisfed.org/series/DCOILWTICO",
     "tgt": "$60-80 = neutral. >$90 = inflation pressure. >$110 = recession risk.",
     "thresholds": {"green": (None, 85), "amber": (85, 105), "red": (105, None)}, "good": "low"},
    {"n": "VIX", "c": "sentiment", "s": ["macro"], "fred_id": "VIXCLS",
     "m": "30-day implied volatility on S&P 500 options.",
     "r": "<15 complacency. 15-25 normal. >30 fear. >40 panic (historically buy zone).",
     "src": "CBOE, FRED (VIXCLS)",
     "tip": "VIX >40 with credit spreads >800 bps = major lows.",
     "link": "https://fred.stlouisfed.org/series/VIXCLS",
     "tgt": "<15 complacency. >30 fear. >40 buy zone.",
     "thresholds": {"green": (None, 20), "amber": (20, 30), "red": (30, None)}, "good": "low"},

    # ============== VALUATION ==============
    {"n": "P/E ratio (trailing)", "c": "valuation", "s": ["value"],
     "m": "Price per share / trailing 12 months EPS.",
     "r": "Compare to sector median, own 5/10yr history, and growth rate. <15 cheap, 15-25 market, >30 priced for growth.",
     "src": "Any data provider",
     "tip": "Useless in isolation. A bank at 8x and a SaaS at 80x can both be expensive or cheap."},
    {"n": "P/E ratio (forward)", "c": "valuation", "s": ["value", "growth"],
     "m": "Price / next 12 months consensus EPS.",
     "r": "Expanding while estimates rise = bullish setup. Expanding while estimates fall = dangerous.",
     "src": "FactSet, Koyfin, TIKR",
     "tip": "Forward estimates are too high ~70% of the time historically."},
    {"n": "PEG ratio (Lynch)", "c": "valuation", "s": ["growth"],
     "m": "P/E divided by EPS growth rate.",
     "r": "<1.0 = potentially undervalued, ~1.0 fair, >2.0 expensive.",
     "src": "Any data provider; One Up On Wall Street",
     "tip": "Use 3-5yr forward growth. Breaks down for high-growth and deep value."},
    {"n": "Price to Sales (P/S)", "c": "valuation", "s": ["value", "growth"],
     "m": "Market cap / revenue.",
     "r": "Useful when earnings are volatile. SaaS often 5-20x, retail 0.5-2x.",
     "src": "Any data provider",
     "tip": "Above 10x P/S, returns barely matter. Above 20x = pricing perfection."},
    {"n": "EV/EBITDA", "c": "valuation", "s": ["value"],
     "m": "Enterprise value / EBITDA. Capital-structure-neutral.",
     "r": "<8x cheap, 8-12x normal, >15x premium. M&A often at 6-10x in mature industries.",
     "src": "Any data provider",
     "tip": "Don't use for capex-heavy biz - EV/FCF is better."},
    {"n": "Free Cash Flow Yield", "c": "valuation", "s": ["value", "quality"],
     "m": "FCF per share / price per share.",
     "r": ">5% with growing FCF = often attractive. >8% for stable biz with capital return = compelling.",
     "src": "Calculate or use Koyfin/Stratosphere",
     "tip": "Pair with ROIC. High FCF yield + high ROIC = compounding machine."},
    {"n": "Price to Book (P/B)", "c": "valuation", "s": ["value"],
     "m": "Price / book value per share.",
     "r": "Classic Graham/Buffett early metric. <1.0 attractive for asset-heavy. Useless for asset-light tech.",
     "src": "Any data provider",
     "tip": "Best for banks, insurers, REITs. P/B + ROE together more useful than P/B alone."},
    {"n": "DCF (Discounted Cash Flow)", "c": "valuation", "s": ["value"],
     "m": "Present value of forecast future free cash flows.",
     "r": "Intrinsic value vs market price. Margin of safety = (intrinsic - price) / intrinsic. Aim 30%+.",
     "src": "Damodaran spreadsheets (free)",
     "tip": "GIGO. Sensitivity-test growth, margins, terminal multiple."},
    {"n": "Reverse DCF", "c": "valuation", "s": ["value", "growth"],
     "m": "Solve for the growth rate implied by today's price.",
     "r": "Implied growth >20% for 10 years = pricing perfection. Compare to TAM realism.",
     "src": "Build in Excel",
     "tip": "Most honest valuation question: 'What does this need to do to justify today's price?'"},

    # ============== QUALITY ==============
    {"n": "Return on Equity (ROE)", "c": "quality", "s": ["quality", "value"],
     "m": "Net income / shareholders' equity.",
     "r": ">15% sustained = good. >20% = excellent. Check leverage (DuPont).",
     "src": "Any data provider",
     "tip": "DuPont: ROE = margin × asset turnover × leverage. Quality firms get ROE from margin, not leverage."},
    {"n": "Return on Invested Capital (ROIC)", "c": "quality", "s": ["quality", "value"],
     "m": "NOPAT / invested capital (debt + equity - cash).",
     "r": ">15% good, >25% excellent. ROIC > WACC = value creation.",
     "src": "Koyfin, Stratosphere",
     "tip": "Single best business quality metric. Buffett: 'A great business earns high returns on capital deployed.'"},
    {"n": "Gross Margin", "c": "quality", "s": ["quality", "growth"],
     "m": "(Revenue - COGS) / Revenue.",
     "r": "Trend matters most. Expanding = pricing power, mix shift, scale. Contracting = pressure.",
     "src": "Income statement",
     "tip": "Munger: 'persistent gross margins above 50% = moat.'"},
    {"n": "Operating Margin", "c": "quality", "s": ["quality"],
     "m": "Operating income / revenue. Opex efficiency.",
     "r": "Compare to peer median. Operating leverage = revenue growing faster than opex.",
     "src": "Income statement",
     "tip": "Companies promising operating leverage but never delivering are lying."},
    {"n": "FCF Margin", "c": "quality", "s": ["quality"],
     "m": "Free cash flow / revenue.",
     "r": ">20% elite. 10-20% healthy. <5% needs scrutiny.",
     "src": "Cash flow statement",
     "tip": "Pair with FCF/Net Income ratio."},
    {"n": "Net Debt / EBITDA", "c": "quality", "s": ["quality"],
     "m": "(Total debt - cash) / EBITDA. Leverage ratio.",
     "r": "<2x conservative. 2-4x normal. >5x stressed. Covenant trigger ~6x.",
     "src": "Calculate",
     "tip": "Most-watched ratio by rating agencies and lenders."},
    {"n": "Interest Coverage", "c": "quality", "s": ["quality"],
     "m": "EBIT / interest expense.",
     "r": ">5x safe. 2-5x OK. <1.5x stressed.",
     "src": "Income statement",
     "tip": "Many zombies that survived ZIRP can't cover at 5% funding."},
    {"n": "FCF Conversion", "c": "quality", "s": ["quality"],
     "m": "FCF / Net Income. How much of reported earnings becomes cash.",
     "r": ">100% high quality. <70% sustained = check accruals, working capital, capex.",
     "src": "Calculate",
     "tip": "Persistent low conversion = earnings quality issue."},
    {"n": "Insider Buying (Form 4)", "c": "quality", "s": ["quality", "value"],
     "m": "Open-market purchases by officers, directors, 10%+ holders.",
     "r": "Cluster buying = strongest signal. CEO/CFO buys carry more weight than single $25k buys.",
     "src": "SEC EDGAR Form 4, OpenInsider.com",
     "tip": "Insiders sell for many reasons. They buy for one.",
     "link": "http://openinsider.com/"},

    # ============== GROWTH ==============
    {"n": "Revenue Growth YoY", "c": "growth", "s": ["growth"],
     "m": "Top-line growth rate vs prior year.",
     "r": "Acceleration beats absolute growth. 20%→30% > steady 50% decelerating.",
     "src": "Income statement",
     "tip": "Revenue acceleration + margin expansion = most powerful 2-variable combo."},
    {"n": "EPS Growth", "c": "growth", "s": ["growth"],
     "m": "Net income per share growth.",
     "r": ">15% forward = growth target. EPS growth from margin expansion is durable; from buybacks alone runs out.",
     "src": "Sell-side consensus",
     "tip": "Watch share count - EPS growth from buybacks is real but lower quality."},
    {"n": "Rule of 40 (SaaS)", "c": "growth", "s": ["growth"],
     "m": "Revenue growth % + FCF margin %.",
     "r": ">40 healthy. >50 elite. <30 = growth or profitability gap.",
     "src": "Calculate from filings",
     "tip": "Single best SaaS quality screen."},
    {"n": "Net Revenue Retention (NRR)", "c": "growth", "s": ["growth"],
     "m": "Revenue from existing customers this year / same cohort last year.",
     "r": ">120% elite. 100-110% good. <100% leaky bucket.",
     "src": "10-K, investor decks",
     "tip": "NRR > 130% commands the highest SaaS multiples."},
    {"n": "Earnings Surprise", "c": "growth", "s": ["growth", "momentum"],
     "m": "Reported EPS vs consensus.",
     "r": "Big beats with raised guidance = strongest setup (PEAD drift).",
     "src": "Earnings Whispers, Estimize",
     "tip": "Reaction matters more than beat itself."},

    # ============== TECHNICAL ==============
    {"n": "Moving Averages (50, 200 DMA)", "c": "technical", "s": ["momentum"],
     "m": "Rolling average closing price.",
     "r": "Price above 200 DMA = long-term uptrend. 50 above 200 = bull confirmed.",
     "src": "TradingView, StockCharts",
     "tip": "Most-traded MA on the planet. Algos respect 200 DMA."},
    {"n": "Golden Cross / Death Cross", "c": "technical", "s": ["momentum"],
     "m": "50 DMA crossing above (golden) or below (death) 200 DMA.",
     "r": "Golden cross marks regime changes. Lagging but reliable for trend confirmation.",
     "src": "Any charting platform",
     "tip": "Great in retrospect, often noisy in real time."},
    {"n": "RSI (14)", "c": "technical", "s": ["momentum"],
     "m": "Momentum oscillator 0-100.",
     "r": ">70 overbought, <30 oversold. Divergences = warning.",
     "src": "Any charting platform",
     "tip": "In strong uptrends RSI stays >70 for weeks. Use divergences over levels."},
    {"n": "MACD (12, 26, 9)", "c": "technical", "s": ["momentum"],
     "m": "Moving Average Convergence Divergence.",
     "r": "MACD crossing above signal = bullish.",
     "src": "Any charting platform",
     "tip": "Weekly MACD crosses more meaningful than daily."},
    {"n": "Stage Analysis (Weinstein)", "c": "technical", "s": ["momentum"],
     "m": "4 stages: 1) Base, 2) Markup, 3) Top, 4) Decline.",
     "r": "Buy only in Stage 2 (price > 30wk MA, MA rising).",
     "src": "Weinstein's Secrets",
     "tip": "Simplest, most underrated framework in trend following."},
    {"n": "Relative Strength vs SPY", "c": "technical", "s": ["momentum"],
     "m": "Stock price / index price ratio.",
     "r": "Rising RS = leadership. New highs in RS = institutional preference.",
     "src": "TradingView, StockCharts",
     "tip": "Buy stocks at new RS highs even if absolute price isn't at ATH."},

    # ============== SENTIMENT ==============
    {"n": "AAII Bull-Bear Spread", "c": "sentiment", "s": ["macro"],
     "m": "Weekly retail investor sentiment survey: bulls minus bears.",
     "r": ">+30 euphoric (contrarian bearish). <-30 panic (contrarian bullish).",
     "src": "AAII.com (free)",
     "tip": "Best contrarian indicator when at extremes.",
     "link": "https://www.aaii.com/sentimentsurvey"},
    {"n": "Put/Call Ratio (Equity)", "c": "sentiment", "s": ["momentum"],
     "m": "Daily ratio of equity put volume to call volume.",
     "r": ">1.0 bearish (contrarian bullish). <0.5 euphoric (contrarian bearish).",
     "src": "CBOE, StockCharts ($CPCE)",
     "tip": "Extreme put/call (>1.2) at oversold market = high-prob bounce setup.",
     "link": "https://stockcharts.com/h-sc/ui?s=%24CPCE"},
    {"n": "NAAIM Exposure Index", "c": "sentiment", "s": ["momentum"],
     "m": "Avg equity exposure of active investment managers, 0-200%.",
     "r": ">80 all-in (late cycle). <30 defensive (often near lows).",
     "src": "naaim.org (free)",
     "tip": "NAAIM bottom decile + AAII bears extreme = near a low.",
     "link": "https://www.naaim.org/programs/naaim-exposure-index/"},
    {"n": "CNN Fear & Greed Index", "c": "sentiment", "s": ["macro"],
     "m": "Composite of 7 sentiment indicators. 0-100.",
     "r": "<20 extreme fear = often buy. >80 extreme greed = often sell.",
     "src": "CNN Business",
     "tip": "Simple, free, surprisingly useful as one-glance check.",
     "link": "https://www.cnn.com/markets/fear-and-greed"},
    {"n": "Short Interest", "c": "sentiment", "s": ["momentum"],
     "m": "% of float sold short.",
     "r": ">20% of float = high SI, squeeze risk. Falling SI + rising price = thesis breaking for shorts.",
     "src": "FINRA, Ortex, S3",
     "tip": "High SI alone isn't a signal. High SI + catalyst + bull tape = squeeze setup."},
    {"n": "13F Hedge Fund Positioning", "c": "sentiment", "s": ["value"],
     "m": "Quarterly disclosures of long positions by funds >$100M AUM.",
     "r": "Crowded longs at peaks = risk. New additions by quality managers = idea generation.",
     "src": "WhaleWisdom, Dataroma",
     "tip": "Buffett's portfolio is most-watched 13F for a reason. 45-day lag.",
     "link": "https://www.dataroma.com/m/home.php"},

    # ============== FRAMEWORKS ==============
    {"n": "Buffett Checklist", "c": "framework", "s": ["value", "quality"],
     "m": "Quality + moat + management + margin of safety + circle of competence.",
     "r": "Owner earnings, 10yr stable ROIC, low debt, durable moat, price < intrinsic.",
     "src": "Berkshire annual letters",
     "tip": "Read Berkshire's 1977-current letters chronologically. Best free MBA on earth.",
     "link": "https://www.berkshirehathaway.com/letters/letters.html"},
    {"n": "Peter Lynch (PEG, story types)", "c": "framework", "s": ["growth", "value"],
     "m": "6 stock types: slow growers, stalwarts, fast growers, cyclicals, turnarounds, asset plays.",
     "r": "Buy what you understand. PEG < 1. Avoid hot stocks in hot industries.",
     "src": "One Up On Wall Street",
     "tip": "'Invest in what you know' means use your edge then DO the work."},
    {"n": "Greenblatt Magic Formula", "c": "framework", "s": ["value"],
     "m": "Rank by EBIT/EV (cheap) + ROIC (good). Buy top 20-30, rebalance annually.",
     "r": "Outperformed historically by ~5pp annualized.",
     "src": "The Little Book That Beats the Market",
     "tip": "Works when you commit to mechanical rules and resist tinkering.",
     "link": "https://www.magicformulainvesting.com/"},
    {"n": "Piotroski F-Score", "c": "framework", "s": ["value", "quality"],
     "m": "9-point checklist within cheapest quintile of book-to-market.",
     "r": "F=8-9 beats F=0-2 by 7.5% annualized in original paper.",
     "src": "Piotroski 2000 paper (SSRN)",
     "tip": "Use as a filter, not a strategy.",
     "link": "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=249455"},
    {"n": "O'Neil CAN SLIM", "c": "framework", "s": ["growth", "momentum"],
     "m": "C, A, N, S, L, I, M - earnings, products, supply/demand, leader, institutional, market.",
     "r": "Quality + growth + chart + market timing combined.",
     "src": "How to Make Money in Stocks",
     "tip": "Pair with Minervini's stage analysis.",
     "link": "https://marketsurge.investors.com/"},
    {"n": "Minervini SEPA Trend Template", "c": "framework", "s": ["momentum", "growth"],
     "m": "8-point trend template + VCP entry pattern.",
     "r": "Strict pre-trade checklist. No buys outside Stage 2.",
     "src": "Trade Like a Stock Market Wizard",
     "tip": "Most underrated trading book of last 20 years.",
     "link": "https://www.minervini.com/"},
    {"n": "Dalio All Weather", "c": "framework", "s": ["macro"],
     "m": "Categorize regime by growth and inflation. Hold balanced exposure to each.",
     "r": "Stocks for growth, TIPS for inflation, bonds for falling growth, gold for stagflation.",
     "src": "Principles by Ray Dalio",
     "tip": "Works because it doesn't try to predict regime.",
     "link": "https://www.bridgewater.com/research-and-insights"},
    {"n": "Howard Marks - Market Cycles", "c": "framework", "s": ["macro", "value"],
     "m": "Two pendulums: greed/fear and risk tolerance.",
     "r": "Late cycle = cheap capital, sloppy DD, building leverage.",
     "src": "Oaktree Memos (free)",
     "tip": "Read every Oaktree memo. Oct 2008 memo called a generational low.",
     "link": "https://www.oaktreecapital.com/insights/memos"},

    # ============== TOOLS ==============
    {"n": "Koyfin", "c": "tool", "s": ["value", "growth", "macro"],
     "m": "Affordable retail/PM-friendly Bloomberg alternative.",
     "r": "Free tier + $40-100/month. Best paid retail tool.",
     "src": "koyfin.com",
     "tip": "Worth every dollar.",
     "link": "https://www.koyfin.com/"},
    {"n": "TIKR Terminal", "c": "tool", "s": ["value", "growth"],
     "m": "Financial modeling + S&P Capital IQ data.",
     "r": "Free tier + $15-40/month.",
     "src": "tikr.com",
     "tip": "Best value for fundamental data at retail price.",
     "link": "https://www.tikr.com/"},
    {"n": "TradingView", "c": "tool", "s": ["momentum", "macro"],
     "m": "Best charting platform.",
     "r": "Free + $15-60/month.",
     "src": "tradingview.com",
     "tip": "Pine Script for custom indicators.",
     "link": "https://www.tradingview.com/"},
    {"n": "FRED (St. Louis Fed)", "c": "tool", "s": ["macro"],
     "m": "800,000+ economic series. Free.",
     "r": "Best macro data source on the internet.",
     "src": "fred.stlouisfed.org",
     "tip": "Build custom dashboards. Single best free finance tool ever made.",
     "link": "https://fred.stlouisfed.org/"},
    {"n": "SEC EDGAR", "c": "tool", "s": ["value", "quality"],
     "m": "Free filings access: 10-K, 10-Q, 8-K, S-1, Form 4, 13F.",
     "r": "Free. Primary-source ground truth.",
     "src": "sec.gov/edgar",
     "tip": "Don't trust summaries - confirm at the source.",
     "link": "https://www.sec.gov/edgar/searchedgar/companysearch"},
    {"n": "Finviz", "c": "tool", "s": ["value", "growth", "momentum"],
     "m": "Free screener, heatmaps, news. Used in this app for RSI + insider data.",
     "r": "Free + Elite ($25/month).",
     "src": "finviz.com",
     "tip": "Best free screener. Daily heatmap is a 5-second market check.",
     "link": "https://finviz.com/"},
    {"n": "Quartr", "c": "tool", "s": ["value", "growth"],
     "m": "Earnings calls + transcripts + investor materials.",
     "r": "Free mobile app + paid tiers.",
     "src": "quartr.com",
     "tip": "Best earnings call app. Listen at 1.5x on your commute.",
     "link": "https://quartr.com/"},
    {"n": "OpenInsider", "c": "tool", "s": ["value", "quality"],
     "m": "Form 4 insider trade aggregator with screens.",
     "r": "Free.",
     "src": "openinsider.com",
     "tip": "Best free insider tracker.",
     "link": "http://openinsider.com/"},
]


def get_by_category(category: str) -> list[dict]:
    return [i for i in INDICATORS if i["c"] == category]


def categories() -> list[str]:
    seen = []
    for i in INDICATORS:
        if i["c"] not in seen:
            seen.append(i["c"])
    return seen
